site_name: Panther
site_description: Fast &  Friendly, Web Framework For Building Async APIs
site_url: https://pantherpy.github.io

theme:
  name: 'material'
  custom_dir: docs
  palette:
    - scheme: 'default'
      media: '(prefers-color-scheme: light)'
      toggle:
        icon: 'material/lightbulb'
        name: 'Switch to dark mode'
    - scheme: 'slate'
      media: '(prefers-color-scheme: dark)'
      primary: 'blue'
      toggle:
        icon: 'material/lightbulb-outline'
        name: 'Switch to light mode'
  icon:
    repo: fontawesome/brands/github

repo_name: AliRn76/Panther
repo_url: https://github.com/AliRn76/Panther
edit_uri: edit/master/docs/

nav:
  - Introduction: 'index.md'
  - First Crud:
      - Function Base: 'function_first_crud.md'
      - Class Base: 'class_first_crud.md'
  - Working With Database: 'working_with_db.md'
  - Panther ODM: 'panther_odm.md'
  - Configs: 'configs.md'
  - WebSocket: 'websocket.md'
  - Monitoring: 'monitoring.md'
  - Log Queries: 'log_queries.md'
  - Middlewares: 'middlewares.md'
  - Authentications: 'authentications.md'
  - URLs: 'urls.md'
  - Throttling: 'throttling.md'
  - Background Tasks: 'background_tasks.md'
#  - Caching: 'caching.md'
#  - UserModel: 'user_model.md'
  - Single-File: 'single_file.md'
  - Release Notes: 'release_notes.md'
  - TODOs: 'todos.md'

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: "#"